name: test
on: pull_request
jobs:
  build:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: swift test
        run: |
          # TODO: @CSolanaM macOS tests not passing because CI screen scale factor is 1, local is 2
          # xcodebuild test -destination platform="macOS" -scheme "SkeletonUISnapshotTests"
          # xcodebuild test -destination name="Apple TV" -scheme "SkeletonUISnapshotTests"
          # xcodebuild test -destination name="Apple TV 4K (3rd generation)" -scheme "SkeletonUISnapshotTests" | xcpretty && exit ${PIPESTATUS[0]}
          xcodebuild test -destination name="iPhone 15 Pro" -scheme "SkeletonUI" | xcpretty && exit ${PIPESTATUS[0]}
