name: test
on: pull_request
jobs:
  build:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: macOS test
        run: |
          sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
