name: test
on: pull_request
jobs:
  build:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: macOS test
        run: |
          '/Library/Application Support/VMWare Tools/vmware-resolutionSet' 2560 1440
