name: test
on: pull_request
jobs:
  build:
    name: test
    runs-on: macOS-12
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: swift test
        run: |
          # TODO: @CSolanaM macOS tests not passing because CI screen scale factor is 1, local is 2
          # xcodebuild test -destination platform="macOS" -scheme "SkeletonUISnapshotTests"
          # xcodebuild test -destination name="Apple TV" -scheme "SkeletonUISnapshotTests"
          # xcodebuild test -destination name="Apple TV 4K (3rd generation)" -scheme "SkeletonUISnapshotTests"
#          xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' -scheme "SkeletonUISnapshotTests" | xcpretty && exit ${PIPESTATUS[0]}
          xcodebuild test -destination name="iPhone 8" -scheme "SkeletonUISnapshotTests" | xcpretty && exit ${PIPESTATUS[0]}
#          xcodebuild test -destination name="iPhone 14 Pro Max" -scheme "SkeletonUISnapshotTests" | xcpretty && exit ${PIPESTATUS[0]}
#          xcodebuild test -destination name="iPad Pro (12.9-inch) (6th generation)" -scheme "SkeletonUISnapshotTests" | xcpretty && exit ${PIPESTATUS[0]}
