name: test
on: pull_request
jobs:
  build:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: macOS test
        run: |
          sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
          sleep 5
          system_profiler SPDisplaysDataType | grep Resolution
          xcodebuild test -destination platform="macOS" -scheme "SkeletonUI"
      - name: tvOS test
        run: |
#          xcodebuild test -destination 'platform=tvOS Simulator,name=Apple TV,OS=17.5' -scheme 'SkeletonUI'
      - name: tvOS 4k test
        run: |
#          xcodebuild test -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=17.5' -scheme 'SkeletonUI'
      - name: iOS test
        run: |
#          xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' -scheme 'SkeletonUI'
